version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_eske
    restart: always
    environment:
      POSTGRES_USER: eske
      POSTGRES_PASSWORD: eske8
      POSTGRES_DB: ticketing
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - microservices-net

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - microservices-net
    restart: unless-stopped

volumes:
  pgdata:
  pgadmin:

networks:
  microservices-net:
    driver: bridge
